name: Kiuwan SAST → TestRail Integration

on:
  push:
    branches:
      - main
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  kiuwan_sast_testrail_integration:
    runs-on: ubuntu-latest
    env:
      APP_NAME: "Kiuwan Sample Java App Scan Demo"
      SRC_PATH: "."
      TESTRAIL_USER: chris.faraglia@gurock.com
      TESTRAIL_URL: https://testrailsademo.testrail.io/
      PROJECT_NAME: TRPD Test Demo
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: '3.10'

      - name: Download Kiuwan Local Analyzer
        run: |
          echo "🔍 Downloading Kiuwan Local Analyzer..."
          curl -sSL "https://www.kiuwan.com/pub/analyzer/KiuwanLocalAnalyzer.zip" -o kla.zip
          unzip -oq kla.zip -d kla

      - name: Run Kiuwan SAST Scan
        env:
          KIUWAN_USER: ${{ secrets.KIUWAN_USER }}
          KIUWAN_PWD: ${{ secrets.KIUWAN_PWD }}
        run: |
          cd kla/KiuwanLocalAnalyzer
          chmod u+x bin/agent.sh
          set +e
          
          echo "🔍 Running Kiuwan scan for $APP_NAME"
          ./bin/agent.sh \
            -s "$SRC_PATH" \
            -n "$APP_NAME" \
            -c \
            -wr \
            -as completeDelivery \
            --user "$KIUWAN_USER" \
            --pass "$KIUWAN_PWD"
          echo "✅ Kiuwan scan finished"

      - name: Fetch Last SAST Scan Code
        id: fetch_delivery
        env:
          KIUWAN_USER: ${{ secrets.KIUWAN_USER }}
          KIUWAN_PWD: ${{ secrets.KIUWAN_PWD }}
          KIUWAN_API: "https://api.kiuwan.com"
        run: |
          echo "🔁 Fetching last successful delivery code from Kiuwan API..."
          # URL-encode the application name safely
          encoded_app=$(printf "%s" "$APP_NAME" | jq -sRr @uri)

          # Perform the API call
          response=$(curl -sSL --user "$KIUWAN_USER:$KIUWAN_PWD" \
            "$KIUWAN_API/deliveries/last_analysis?application=$encoded_app")
          
          echo "📦 Raw API response:"
          echo "$response"

          # Try to extract delivery code from multiple possible fields
          code=$(echo "$response" | jq -r '.lastSuccessfulDelivery.code // .analysisCode // empty')

          if [ -z "$code" ] || [ "$code" = "null" ]; then
            echo "⚠️ Unable to extract lastSuccessfulDelivery.analysisCode from response"
            exit 1
          fi

          echo "🏷 Last Successful Delivery Code: $code"
          echo "delivery_code=$code" >> $GITHUB_OUTPUT

      - name: Print Last SAST Scan Code (INFO LOGGING)
        run: |
          echo "🚀 Last Successful Delivery Code: ${{ steps.fetch_delivery.outputs.delivery_code }}"

      - name: Download JUnit XML Report From Kiuwan SAST Scan
        id: fetch_junit
        env:
          KIUWAN_USER: ${{ secrets.KIUWAN_USER }}
          KIUWAN_PWD: ${{ secrets.KIUWAN_PWD }}
          KIUWAN_API: "https://api.kiuwan.com"
          DELIVERY_CODE: ${{ steps.fetch_delivery.outputs.delivery_code }}
        run: |
          echo "🧩 Fetching JUnit XML for delivery code: $DELIVERY_CODE"
          curl -sSL --user "$KIUWAN_USER:$KIUWAN_PWD" \
            "$KIUWAN_API/deliveries/junit?deliveryCode=$DELIVERY_CODE" \
            -o kiuwan_sast.xml

          if [ ! -s kiuwan_sast.xml ]; then
            echo "❌ Failed to retrieve kiuwan_sast.xml"
            exit 1
          fi

          echo "✅ JUnit XML saved as kiuwan_sast.xml"

      - name: Upload JUnit XML as artifact
        uses: actions/upload-artifact@v4
        with:
          name: kiuwan-sast-report
          path: kiuwan_sast.xml
          
      - name: Execute TestRail CLI to upload results
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          pip install trcli
          trcli -y \
            -h ${{ env.TESTRAIL_URL }} \
            --project "${{ env.PROJECT_NAME }}" \
            -u ${{ env.TESTRAIL_USER }} \
            -p "${{ secrets.TESTRAIL_USER_PW }}" \
            parse_junit \
            -f "kiuwan_sast.xml" \
            --title "Kiuwan SAST Audit Checkpoint Tests"
